package com.EmployeesDB.model.impl;

import com.EmployeesDB.model.Bank;
import com.EmployeesDB.model.BankModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the Bank service. Represents a row in the &quot;testtask_Bank&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.EmployeesDB.model.BankModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link BankImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see BankImpl
 * @see com.EmployeesDB.model.Bank
 * @see com.EmployeesDB.model.BankModel
 * @generated
 */
public class BankModelImpl extends BaseModelImpl<Bank> implements BankModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a bank model instance should use the {@link com.EmployeesDB.model.Bank} interface instead.
     */
    public static final String TABLE_NAME = "testtask_Bank";
    public static final Object[][] TABLE_COLUMNS = {
            { "bankId", Types.BIGINT },
            { "bankName", Types.VARCHAR },
            { "bik", Types.VARCHAR },
            { "adres", Types.VARCHAR }
        };
    public static final String TABLE_SQL_CREATE = "create table testtask_Bank (bankId LONG not null primary key,bankName VARCHAR(75) null,bik VARCHAR(75) null,adres VARCHAR(75) null)";
    public static final String TABLE_SQL_DROP = "drop table testtask_Bank";
    public static final String ORDER_BY_JPQL = " ORDER BY bank.bankId ASC";
    public static final String ORDER_BY_SQL = " ORDER BY testtask_Bank.bankId ASC";
    public static final String DATA_SOURCE = "liferayDataSource";
    public static final String SESSION_FACTORY = "liferaySessionFactory";
    public static final String TX_MANAGER = "liferayTransactionManager";
    public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.entity.cache.enabled.com.EmployeesDB.model.Bank"),
            true);
    public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.finder.cache.enabled.com.EmployeesDB.model.Bank"),
            true);
    public static final boolean COLUMN_BITMASK_ENABLED = false;
    public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
                "lock.expiration.time.com.EmployeesDB.model.Bank"));
    private static ClassLoader _classLoader = Bank.class.getClassLoader();
    private static Class<?>[] _escapedModelInterfaces = new Class[] { Bank.class };
    private long _bankId;
    private String _bankName;
    private String _bik;
    private String _adres;
    private Bank _escapedModel;

    public BankModelImpl() {
    }

    @Override
    public long getPrimaryKey() {
        return _bankId;
    }

    @Override
    public void setPrimaryKey(long primaryKey) {
        setBankId(primaryKey);
    }

    @Override
    public Serializable getPrimaryKeyObj() {
        return _bankId;
    }

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj) {
        setPrimaryKey(((Long) primaryKeyObj).longValue());
    }

    @Override
    public Class<?> getModelClass() {
        return Bank.class;
    }

    @Override
    public String getModelClassName() {
        return Bank.class.getName();
    }

    @Override
    public Map<String, Object> getModelAttributes() {
        Map<String, Object> attributes = new HashMap<String, Object>();

        attributes.put("bankId", getBankId());
        attributes.put("bankName", getBankName());
        attributes.put("bik", getBik());
        attributes.put("adres", getAdres());

        return attributes;
    }

    @Override
    public void setModelAttributes(Map<String, Object> attributes) {
        Long bankId = (Long) attributes.get("bankId");

        if (bankId != null) {
            setBankId(bankId);
        }

        String bankName = (String) attributes.get("bankName");

        if (bankName != null) {
            setBankName(bankName);
        }

        String bik = (String) attributes.get("bik");

        if (bik != null) {
            setBik(bik);
        }

        String adres = (String) attributes.get("adres");

        if (adres != null) {
            setAdres(adres);
        }
    }

    @Override
    public long getBankId() {
        return _bankId;
    }

    @Override
    public void setBankId(long bankId) {
        _bankId = bankId;
    }

    @Override
    public String getBankName() {
        if (_bankName == null) {
            return StringPool.BLANK;
        } else {
            return _bankName;
        }
    }

    @Override
    public void setBankName(String bankName) {
        _bankName = bankName;
    }

    @Override
    public String getBik() {
        if (_bik == null) {
            return StringPool.BLANK;
        } else {
            return _bik;
        }
    }

    @Override
    public void setBik(String bik) {
        _bik = bik;
    }

    @Override
    public String getAdres() {
        if (_adres == null) {
            return StringPool.BLANK;
        } else {
            return _adres;
        }
    }

    @Override
    public void setAdres(String adres) {
        _adres = adres;
    }

    @Override
    public ExpandoBridge getExpandoBridge() {
        return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
            Bank.class.getName(), getPrimaryKey());
    }

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
        ExpandoBridge expandoBridge = getExpandoBridge();

        expandoBridge.setAttributes(serviceContext);
    }

    @Override
    public Bank toEscapedModel() {
        if (_escapedModel == null) {
            _escapedModel = (Bank) ProxyUtil.newProxyInstance(_classLoader,
                    _escapedModelInterfaces, new AutoEscapeBeanHandler(this));
        }

        return _escapedModel;
    }

    @Override
    public Object clone() {
        BankImpl bankImpl = new BankImpl();

        bankImpl.setBankId(getBankId());
        bankImpl.setBankName(getBankName());
        bankImpl.setBik(getBik());
        bankImpl.setAdres(getAdres());

        bankImpl.resetOriginalValues();

        return bankImpl;
    }

    @Override
    public int compareTo(Bank bank) {
        long primaryKey = bank.getPrimaryKey();

        if (getPrimaryKey() < primaryKey) {
            return -1;
        } else if (getPrimaryKey() > primaryKey) {
            return 1;
        } else {
            return 0;
        }
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }

        if (!(obj instanceof Bank)) {
            return false;
        }

        Bank bank = (Bank) obj;

        long primaryKey = bank.getPrimaryKey();

        if (getPrimaryKey() == primaryKey) {
            return true;
        } else {
            return false;
        }
    }

    @Override
    public int hashCode() {
        return (int) getPrimaryKey();
    }

    @Override
    public void resetOriginalValues() {
    }

    @Override
    public CacheModel<Bank> toCacheModel() {
        BankCacheModel bankCacheModel = new BankCacheModel();

        bankCacheModel.bankId = getBankId();

        bankCacheModel.bankName = getBankName();

        String bankName = bankCacheModel.bankName;

        if ((bankName != null) && (bankName.length() == 0)) {
            bankCacheModel.bankName = null;
        }

        bankCacheModel.bik = getBik();

        String bik = bankCacheModel.bik;

        if ((bik != null) && (bik.length() == 0)) {
            bankCacheModel.bik = null;
        }

        bankCacheModel.adres = getAdres();

        String adres = bankCacheModel.adres;

        if ((adres != null) && (adres.length() == 0)) {
            bankCacheModel.adres = null;
        }

        return bankCacheModel;
    }

    @Override
    public String toString() {
        StringBundler sb = new StringBundler(9);

        sb.append("{bankId=");
        sb.append(getBankId());
        sb.append(", bankName=");
        sb.append(getBankName());
        sb.append(", bik=");
        sb.append(getBik());
        sb.append(", adres=");
        sb.append(getAdres());
        sb.append("}");

        return sb.toString();
    }

    @Override
    public String toXmlString() {
        StringBundler sb = new StringBundler(16);

        sb.append("<model><model-name>");
        sb.append("com.EmployeesDB.model.Bank");
        sb.append("</model-name>");

        sb.append(
            "<column><column-name>bankId</column-name><column-value><![CDATA[");
        sb.append(getBankId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>bankName</column-name><column-value><![CDATA[");
        sb.append(getBankName());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>bik</column-name><column-value><![CDATA[");
        sb.append(getBik());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>adres</column-name><column-value><![CDATA[");
        sb.append(getAdres());
        sb.append("]]></column-value></column>");

        sb.append("</model>");

        return sb.toString();
    }
}
