package com.EmployeesDB.model.impl;

import com.EmployeesDB.model.Employees;

import com.EmployeesDB.service.EmployeesLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the Employees service. Represents a row in the &quot;testtask_Employees&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EmployeesImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EmployeesImpl
 * @see com.EmployeesDB.model.Employees
 * @generated
 */
public abstract class EmployeesBaseImpl extends EmployeesModelImpl
    implements Employees {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a employees model instance should use the {@link Employees} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            EmployeesLocalServiceUtil.addEmployees(this);
        } else {
            EmployeesLocalServiceUtil.updateEmployees(this);
        }
    }
}
