package com.EmployeesDB.model.impl;

import com.EmployeesDB.model.Positions;

import com.EmployeesDB.service.PositionsLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the Positions service. Represents a row in the &quot;testtask_Positions&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PositionsImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PositionsImpl
 * @see com.EmployeesDB.model.Positions
 * @generated
 */
public abstract class PositionsBaseImpl extends PositionsModelImpl
    implements Positions {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a positions model instance should use the {@link Positions} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            PositionsLocalServiceUtil.addPositions(this);
        } else {
            PositionsLocalServiceUtil.updatePositions(this);
        }
    }
}
