package com.EmployeesDB.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Employees service. Represents a row in the &quot;testtask_Employees&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.EmployeesDB.model.impl.EmployeesModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.EmployeesDB.model.impl.EmployeesImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Employees
 * @see com.EmployeesDB.model.impl.EmployeesImpl
 * @see com.EmployeesDB.model.impl.EmployeesModelImpl
 * @generated
 */
public interface EmployeesModel extends BaseModel<Employees> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a employees model instance should use the {@link Employees} interface instead.
     */

    /**
     * Returns the primary key of this employees.
     *
     * @return the primary key of this employees
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this employees.
     *
     * @param primaryKey the primary key of this employees
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the emp ID of this employees.
     *
     * @return the emp ID of this employees
     */
    public long getEmpId();

    /**
     * Sets the emp ID of this employees.
     *
     * @param empId the emp ID of this employees
     */
    public void setEmpId(long empId);

    /**
     * Returns the first name of this employees.
     *
     * @return the first name of this employees
     */
    @AutoEscape
    public String getFirstName();

    /**
     * Sets the first name of this employees.
     *
     * @param firstName the first name of this employees
     */
    public void setFirstName(String firstName);

    /**
     * Returns the second name of this employees.
     *
     * @return the second name of this employees
     */
    @AutoEscape
    public String getSecondName();

    /**
     * Sets the second name of this employees.
     *
     * @param secondName the second name of this employees
     */
    public void setSecondName(String secondName);

    /**
     * Returns the last name of this employees.
     *
     * @return the last name of this employees
     */
    @AutoEscape
    public String getLastName();

    /**
     * Sets the last name of this employees.
     *
     * @param lastName the last name of this employees
     */
    public void setLastName(String lastName);

    /**
     * Returns the gender of this employees.
     *
     * @return the gender of this employees
     */
    @AutoEscape
    public String getGender();

    /**
     * Sets the gender of this employees.
     *
     * @param gender the gender of this employees
     */
    public void setGender(String gender);

    /**
     * Returns the birthday of this employees.
     *
     * @return the birthday of this employees
     */
    public Date getBirthday();

    /**
     * Sets the birthday of this employees.
     *
     * @param birthday the birthday of this employees
     */
    public void setBirthday(Date birthday);

    /**
     * Returns the empl position of this employees.
     *
     * @return the empl position of this employees
     */
    public long getEmplPosition();

    /**
     * Sets the empl position of this employees.
     *
     * @param emplPosition the empl position of this employees
     */
    public void setEmplPosition(long emplPosition);

    /**
     * Returns the start work of this employees.
     *
     * @return the start work of this employees
     */
    public Date getStartWork();

    /**
     * Sets the start work of this employees.
     *
     * @param startWork the start work of this employees
     */
    public void setStartWork(Date startWork);

    /**
     * Returns the salary of this employees.
     *
     * @return the salary of this employees
     */
    public long getSalary();

    /**
     * Sets the salary of this employees.
     *
     * @param salary the salary of this employees
     */
    public void setSalary(long salary);

    /**
     * Returns the work phone number of this employees.
     *
     * @return the work phone number of this employees
     */
    @AutoEscape
    public String getWorkPhoneNumber();

    /**
     * Sets the work phone number of this employees.
     *
     * @param workPhoneNumber the work phone number of this employees
     */
    public void setWorkPhoneNumber(String workPhoneNumber);

    /**
     * Returns the phone number of this employees.
     *
     * @return the phone number of this employees
     */
    @AutoEscape
    public String getPhoneNumber();

    /**
     * Sets the phone number of this employees.
     *
     * @param phoneNumber the phone number of this employees
     */
    public void setPhoneNumber(String phoneNumber);

    /**
     * Returns the bank of this employees.
     *
     * @return the bank of this employees
     */
    public long getBank();

    /**
     * Sets the bank of this employees.
     *
     * @param bank the bank of this employees
     */
    public void setBank(long bank);

    /**
     * Returns the is archived of this employees.
     *
     * @return the is archived of this employees
     */
    public boolean getIsArchived();

    /**
     * Returns <code>true</code> if this employees is is archived.
     *
     * @return <code>true</code> if this employees is is archived; <code>false</code> otherwise
     */
    public boolean isIsArchived();

    /**
     * Sets whether this employees is is archived.
     *
     * @param isArchived the is archived of this employees
     */
    public void setIsArchived(boolean isArchived);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(Employees employees);

    @Override
    public int hashCode();

    @Override
    public CacheModel<Employees> toCacheModel();

    @Override
    public Employees toEscapedModel();

    @Override
    public Employees toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
